
  CREATE TABLE "QUARTERMEAT"."CUSTOMERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREDITCARDNUMBER" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RESERVATION" NUMBER, 
	 CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CUSTOMERS_UK1" UNIQUE ("CREDITCARDNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CUSTOMERS_FK1" FOREIGN KEY ("RESERVATION")
	  REFERENCES "QUARTERMEAT"."RESERVATIONS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE OR REPLACE TRIGGER "QUARTERMEAT"."AUTO_customers_TRIGGER" 
BEFORE INSERT ON customers
FOR EACH ROW

BEGIN
  SELECT AUTO_INCREMENT.NEXTVAL
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "QUARTERMEAT"."AUTO_customers_TRIGGER" ENABLE;
